/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Background: typeof import('./src/components/Background.vue')['default']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRow: typeof import('element-plus/es')['ElRow']
    Hitokoto: typeof import('./src/components/Hitokoto.vue')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheDayWord: typeof import('./src/components/theDayWord.vue')['default']
    TheDayWordStatus: typeof import('./src/components/theDayWordStatus.vue')['default']
    Weather: typeof import('./src/components/weather.vue')['default']
  }
}
